import {lazy,Suspense,useMemo,useState} from 'react';
import {ArrowUpRight,ChevronRight,Eye,Focus,Layers3,Maximize2,RotateCcw,Search,SlidersHorizontal,X} from 'lucide-react';
import {SYSTEMS,type Atlas,type Concept} from '../anatomy';
import {createAnatomyIndex,organNames,presets,type AnatomyAngle,type AnatomyPreset,type AnatomyRegion,type PhysicalViewState} from '../physical/anatomy-view';
import type {BodyState,Organ} from './types';
import '../physical/physical.css';
const PhysicalScene=lazy(()=>import('../physical/PhysicalScene'));
const organs=Object.keys(organNames) as Organ[];
const initialView:PhysicalViewState={preset:'dissection',region:'body',angle:'front',selected:[],isolate:false,context:.5,cut:'none',slice:.5,reset:0,focus:0,hidden:[]};
export default function BodyMap({state,selected,onSelect,layer,atlas,onAnatomy}:{state:BodyState;selected:Organ;onSelect:(id:Organ)=>void;running:boolean;layer:'flow'|'oxygen'|'hormones';atlas:Atlas|null;onAnatomy:(query?:string)=>void}) {
 const [view,setView]=useState(initialView),[progress,setProgress]=useState(0),[error,setError]=useState(''),[query,setQuery]=useState(''),[structure,setStructure]=useState<Concept|null>(null),[toolsOpen,setToolsOpen]=useState(false),[expanded,setExpanded]=useState(false);
 const index=useMemo(()=>atlas?createAnatomyIndex(atlas):null,[atlas]);
 const parts=structure?.elements??[...(index?.groups[selected]??[])];
 const sceneView=useMemo(()=>({...view,selected:parts}),[view,structure,index,selected]);
 const preset=presets.find(p=>p.id===view.preset)!;
 const searchResults=useMemo(()=>{if(!atlas||query.trim().length<2)return [];const q=query.toLowerCase().trim();return atlas.concepts.filter(c=>c.name.toLowerCase().includes(q)||c.id.toLowerCase().includes(q)).sort((a,b)=>Number(b.name.toLowerCase()===q)-Number(a.name.toLowerCase()===q)||a.name.length-b.name.length).slice(0,12);},[atlas,query]);
 const selectOrgan=(id:Organ)=>{setStructure(null);onSelect(id);setView(v=>({...v,isolate:false,hidden:[],focus:v.focus+1,region:v.region==='selection'?'body':v.region,preset:id==='skin'?'surface':id==='muscle'?'muscles':v.preset==='surface'||v.preset==='muscles'?'dissection':v.preset}));};
 const selectStructure=(c:Concept)=>{setStructure(c);setQuery('');setView(v=>({...v,region:'selection',isolate:true,hidden:[],cut:'none',focus:v.focus+1}));const organ=c.elements.map(id=>index?.organ.get(id)).find(Boolean);if(organ)onSelect(organ);};
 const pick=(id:string)=>{const part=atlas?.parts.find(p=>p.id===id);if(!part)return;setStructure({id:part.conceptId,name:part.name,elements:[id]});const organ=index?.organ.get(id);if(organ)onSelect(organ);};
 const reset=()=>{setView(v=>({...initialView,reset:v.reset+1}));setStructure(null);setQuery('');};
 const value=(id:Organ)=>{
  const flow=state.flows.find(f=>f.id===id);
  if(layer==='flow')return `${(flow?.flow??0).toFixed(2)} L/min`;
  if(layer==='oxygen')return id==='lungs'?`${state.saturation.toFixed(1)}% arterial`:`${(flow?.oxygenUse??0).toFixed(0)} mL/min`;
  const key={heart:'epinephrine',lungs:'norepinephrine',brain:'cortisol',liver:'glucagon',gut:'cck',kidneys:'adh',muscle:'insulin',skin:'thyroid',adipose:'leptin',endocrine:'tsh'} as const;
  return `${key[id].toUpperCase()} ${state.hormones[key[id]].toFixed(2)}×`;
 };
 return <div className={`physical-anatomy ${expanded?'physical-expanded':''}`}>
  <div className="physical-header"><div><span>ANATOMICAL EXPLORER</span><h2>The human body<span> / in three dimensions</span></h2></div><button onClick={()=>setExpanded(e=>!e)} aria-label={expanded?'Exit expanded anatomy':'Expand anatomy'} title={expanded?'Exit expanded anatomy':'Expand anatomy'}>{expanded?<X size={17}/>:<Maximize2 size={17}/>}</button></div>
  <div className="physical-presets" role="group" aria-label="Anatomical layers">{presets.map(p=><button key={p.id} aria-pressed={view.preset===p.id} onClick={()=>{setStructure(null);setView(v=>({...v,preset:p.id,isolate:false,hidden:[],cut:'none'}));}}>{p.name}</button>)}</div>
  <div className="physical-stage">
   {atlas&&<Suspense fallback={null}><PhysicalScene atlas={atlas} view={sceneView} onSelect={pick} onProgress={setProgress} onError={setError}/></Suspense>}
   <div className="physical-stage-heading"><span>{view.isolate?'ISOLATED STRUCTURE':preset.name.toUpperCase()}</span><p>{view.isolate?structure?.name??organNames[selected]:preset.description}</p></div>
   <div className="physical-search"><Search size={14}/><input aria-label="Search physical anatomy" placeholder="Find a structure…" value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>{if(e.key==='Escape')setQuery('');}}/>{query&&<button aria-label="Clear anatomy search" onClick={()=>setQuery('')}><X size={13}/></button>}{query.trim().length>=2&&<div className="physical-results">{searchResults.length?searchResults.map(c=><button key={c.id} onClick={()=>selectStructure(c)}><span>{c.name}</span><small>{c.elements.length} {c.elements.length===1?'part':'parts'}</small><ChevronRight size={12}/></button>):<p>No source structure found.</p>}</div>}</div>
   <div className="physical-orientation" aria-label="Anatomy camera angle">{(['front','oblique','back','side'] as AnatomyAngle[]).map(angle=><button key={angle} aria-pressed={view.angle===angle} onClick={()=>setView(v=>({...v,angle}))}>{angle==='front'?'Anterior':angle==='back'?'Posterior':angle==='side'?'Lateral':'¾ view'}</button>)}</div>
   <div className="physical-regions" role="group" aria-label="Anatomy region">{([{id:'body',name:'Full body'},{id:'torso',name:'Thorax'},{id:'abdomen',name:'Abdomen'},{id:'head',name:'Head & neck'}] as {id:AnatomyRegion;name:string}[]).map(r=><button key={r.id} aria-pressed={view.region===r.id&&!view.isolate} onClick={()=>setView(v=>({...v,region:r.id,isolate:false,focus:v.focus+1}))}>{r.name}</button>)}</div>
   <div className="physical-stage-actions"><button onClick={()=>setToolsOpen(v=>!v)} aria-expanded={toolsOpen}><SlidersHorizontal size={15}/> Dissect</button><button aria-label="Reset anatomy view" onClick={reset}><RotateCcw size={15}/></button></div>
   {toolsOpen&&<div className="physical-tools"><div><strong>Dissection controls</strong><button aria-label="Close dissection controls" onClick={()=>setToolsOpen(false)}><X size={13}/></button></div><label>Section plane<select aria-label="Anatomical section plane" value={view.cut} onChange={e=>setView(v=>({...v,cut:e.target.value as PhysicalViewState['cut']}))}><option value="none">None</option><option value="sagittal">Sagittal · left / right</option><option value="coronal">Coronal · front / back</option><option value="axial">Axial · upper / lower</option></select></label>{view.cut!=='none'&&<label>Section position<input aria-label="Anatomical section position" type="range" min="0" max="1" step=".01" value={view.slice} onChange={e=>setView(v=>({...v,slice:Number(e.target.value)}))}/></label>}<label>Skeleton context<input aria-label="Skeleton context opacity" type="range" min="0" max="1" step=".05" value={view.context} onChange={e=>setView(v=>({...v,context:Number(e.target.value)}))}/></label><p>Context opacity applies to Organs, Vessels and Nerves. Section planes expose source surfaces; cut faces are open.</p>{view.hidden.length>0&&<button onClick={()=>setView(v=>({...v,hidden:[]}))}>Restore {view.hidden.length} hidden parts</button>}</div>}
   {progress<100&&!error&&<div className="physical-loading" role="status"><Layers3 size={25}/><strong>Assembling the anatomy</strong><span>{progress}% · Loading source geometry</span><div><i style={{width:`${progress}%`}}/></div></div>}
   {error&&<div className="physical-loading physical-load-error" role="alert"><strong>{error}</strong><button onClick={()=>onAnatomy()}>Open anatomy workspace <ArrowUpRight size={14}/></button></div>}
   <div className="physical-scale" aria-hidden="true"><i/><span>SUPERIOR</span><span>INFERIOR</span></div>
   <div className="physical-stage-foot"><span>Drag to orbit · Scroll to zoom · Click to inspect</span><span>BodyParts3D · Adult male</span></div>
  </div>
  <div className="physical-selection"><div><span>{structure?'SELECTED STRUCTURE':'SELECTED PHYSIOLOGY'}</span><h3>{structure?.name??organNames[selected]}</h3><p>{parts.length?`${parts.length.toLocaleString()} source ${parts.length===1?'mesh':'meshes'}${structure?` · ${structure.id}`:''}`:'No dedicated geometry in this atlas'}</p></div><div className="physical-selection-actions"><button disabled={!parts.length} onClick={()=>setView(v=>({...v,region:'selection',focus:v.focus+1}))}><Focus size={14}/> Focus</button><button disabled={!parts.length} aria-pressed={view.isolate} onClick={()=>setView(v=>({...v,isolate:!v.isolate,region:!v.isolate?'selection':'body',focus:v.focus+1,cut:'none'}))}><Eye size={14}/> {view.isolate?'In context':'Isolate'}</button>{structure&&<button onClick={()=>{setView(v=>({...v,hidden:[...new Set([...v.hidden,...parts])],isolate:false,region:v.region==='selection'?'body':v.region}));setStructure(null);}}>Hide</button>}<button aria-label="Open selected structure in full atlas" onClick={()=>onAnatomy(structure?.name??({gut:'small intestine',muscle:'skeletal muscle',endocrine:'pituitary gland',kidneys:'kidney',lungs:'lung'} as Partial<Record<Organ,string>>)[selected]??organNames[selected])}><ArrowUpRight size={16}/></button></div></div>
  <div className="physical-live-heading"><span><i/> LIVE ORGAN READOUTS</span><small>{layer==='flow'?'Blood flow':layer==='oxygen'?'Oxygen use':'Relative hormone activity'} · organ compartments</small></div>
  <div className="physical-organ-list">{organs.map(id=><button key={id} aria-label={`Inspect ${organNames[id]}`} aria-pressed={selected===id&&!structure} onClick={()=>selectOrgan(id)}><span>{organNames[id]}</span><strong>{value(id)}</strong></button>)}</div>
  <div className="physical-credit"><span>{atlas?.parts.length.toLocaleString()??'2,234'} source meshes · {SYSTEMS.length} systems · {((atlas?.triangles??2288268)/1000000).toFixed(2)}M triangles</span><a href="/ATTRIBUTION.md" target="_blank" rel="noreferrer">Source & attribution ↗</a></div>
 </div>;
}
