import {lazy,Suspense,useEffect,useMemo,useRef,useState} from 'react';
import {ArrowUpRight,ChevronRight,Eye,Focus,Layers3,Maximize2,RotateCcw,Search,SlidersHorizontal,X,Play,Pause,Heart,Wind,Utensils} from 'lucide-react';
import {SYSTEMS,type Atlas,type Concept} from '../anatomy';
import {createAnatomyIndex,organNames,presets,type AnatomyAngle,type AnatomyPreset,type AnatomyRegion,type PhysicalViewState} from '../physical/anatomy-view';
import type {BodyState,Organ} from './types';
import '../physical/physical.css';
const PhysicalScene=lazy(()=>import('../physical/PhysicalScene'));
const organs=Object.keys(organNames) as Organ[];
const initialView:PhysicalViewState={preset:'dissection',region:'body',angle:'front',selected:[],isolate:false,context:.5,cut:'none',slice:.5,reset:0,focus:0,hidden:[]};
export default function BodyMap({state,selected,onSelect,layer,atlas,onAnatomy,running,catalogueError}:{state:BodyState;selected:Organ;onSelect:(id:Organ)=>void;running:boolean;layer:'flow'|'oxygen'|'hormones';atlas:Atlas|null;catalogueError?:string;onAnatomy:(query?:string)=>void}) {
 const [view,setView]=useState(initialView),[progress,setProgress]=useState(0),[error,setError]=useState(''),[query,setQuery]=useState(''),[structure,setStructure]=useState<Concept|null>(null),[toolsOpen,setToolsOpen]=useState(false),[expanded,setExpanded]=useState(false),[motion,setMotion]=useState(()=>!window.matchMedia('(prefers-reduced-motion: reduce)').matches);
 const root=useRef<HTMLDivElement>(null),expandButton=useRef<HTMLButtonElement>(null);
 useEffect(()=>{if(!expanded)return;const previous=document.body.style.overflow;document.body.style.overflow='hidden';expandButton.current?.focus();const key=(e:KeyboardEvent)=>{if(e.key==='Escape'){setExpanded(false);return;}if(e.key==='Tab'){const items=[...root.current!.querySelectorAll<HTMLElement>('button:not(:disabled),input,select,a')].filter(el=>el.getClientRects().length);const first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}};window.addEventListener('keydown',key);return()=>{document.body.style.overflow=previous;window.removeEventListener('keydown',key);expandButton.current?.focus();};},[expanded]);
 const index=useMemo(()=>atlas?createAnatomyIndex(atlas):null,[atlas]);
 const parts=structure?.elements??[...(index?.groups[selected]??[])];
 const sceneView=useMemo(()=>({...view,selected:parts}),[view,structure,index,selected]);
 const displayError=error||catalogueError;
 const preset=presets.find(p=>p.id===view.preset)!;
 const searchResults=useMemo(()=>{if(!atlas||query.trim().length<2)return [];const q=query.toLowerCase().trim();return atlas.concepts.filter(c=>c.name.toLowerCase().includes(q)||c.id.toLowerCase().includes(q)).sort((a,b)=>Number(b.name.toLowerCase()===q)-Number(a.name.toLowerCase()===q)||a.name.length-b.name.length).slice(0,12);},[atlas,query]);
 const selectOrgan=(id:Organ)=>{setStructure(null);onSelect(id);setView(v=>({...v,isolate:false,hidden:[],focus:v.focus+1,region:v.region==='selection'?'body':v.region,preset:id==='skin'?'surface':id==='muscle'?'muscles':v.preset==='surface'||v.preset==='muscles'?'dissection':v.preset}));};
 const selectStructure=(c:Concept)=>{setStructure(c);setQuery('');setView(v=>({...v,region:'selection',isolate:true,hidden:[],cut:'none',focus:v.focus+1}));const organ=c.elements.map(id=>index?.organ.get(id)).find(Boolean);if(organ)onSelect(organ);};
 const pick=(id:string)=>{const part=atlas?.parts.find(p=>p.id===id);if(!part)return;setStructure({id:part.conceptId,name:part.name,elements:[id]});const organ=index?.organ.get(id);if(organ)onSelect(organ);};
 const watch=(id:Organ,preset:AnatomyPreset)=>{setStructure(null);onSelect(id);setMotion(true);setView(v=>({...v,preset,region:id==='gut'?'abdomen':id==='lungs'?'selection':'torso',isolate:false,cut:'none',hidden:[],focus:v.focus+1}));};
 const reset=()=>{setView(v=>({...initialView,reset:v.reset+1}));setStructure(null);setQuery('');};
 const value=(id:Organ)=>{
  const flow=state.flows.find(f=>f.id===id);
  if(layer==='flow')return `${(flow?.flow??0).toFixed(2)} L/min`;
  if(layer==='oxygen')return id==='lungs'?`${state.saturation.toFixed(1)}% arterial`:`${(flow?.oxygenUse??0).toFixed(0)} mL/min`;
  const key={heart:'epinephrine',lungs:'norepinephrine',brain:'cortisol',liver:'glucagon',gut:'cck',kidneys:'adh',muscle:'insulin',skin:'thyroid',adipose:'leptin',endocrine:'tsh'} as const;
  return `${key[id].toUpperCase()} ${state.hormones[key[id]].toFixed(2)}×`;
 };
 return <div ref={root} role={expanded?'dialog':undefined} aria-modal={expanded?true:undefined} aria-label={expanded?'Expanded physical anatomy':undefined} className={`physical-anatomy ${expanded?'physical-expanded':''}`}>
  <div className="physical-header"><div><span>ANATOMICAL EXPLORER</span><h2>The human body<span> / in three dimensions</span></h2></div><button ref={expandButton} onClick={()=>setExpanded(e=>!e)} aria-label={expanded?'Exit expanded anatomy':'Expand anatomy'} title={expanded?'Exit expanded anatomy':'Expand anatomy'}>{expanded?<X size={17}/>:<Maximize2 size={17}/>}</button></div>
  <div className="physical-presets" role="group" aria-label="Anatomical layers">{presets.map(p=><button key={p.id} aria-pressed={view.preset===p.id} onClick={()=>{setStructure(null);setView(v=>({...v,preset:p.id,isolate:false,hidden:[],cut:'none'}));}}>{p.name}</button>)}</div>
  <div className="physical-processes"><button aria-label="Watch circulation" onClick={()=>watch('heart','vessels')}><Heart size={15}/><span>Circulation<strong>{state.heartRate.toFixed(0)} <small>bpm</small></strong></span><svg viewBox="0 0 70 25" aria-hidden="true"><path d="M0 14H17L22 10L26 18L31 3L36 23L40 14H70"/></svg></button><button aria-label="Watch breathing" onClick={()=>watch('lungs','organs')}><Wind size={15}/><span>Breathing<strong>{state.respiratoryRate.toFixed(1)} <small>/min</small></strong></span><small>{state.tidalVolume.toFixed(0)} mL / breath</small></button><button aria-label="Watch digestion" onClick={()=>watch('gut','organs')}><Utensils size={15}/><span>Digestion<strong>{(state.digestionRates.carbs+state.digestionRates.protein+state.digestionRates.fat).toFixed(2)} <small>g/min</small></strong></span><small>{state.stomach.carbs+state.stomach.protein+state.stomach.fat>0?'Processing meal':'Between meals'}</small></button></div>
  <div className="physical-stage">
   {atlas&&<Suspense fallback={null}><PhysicalScene atlas={atlas} body={state} motion={motion} view={sceneView} onSelect={pick} onProgress={setProgress} onError={setError}/></Suspense>}
   <div className="physical-stage-heading"><span>{view.isolate?'ISOLATED STRUCTURE':preset.name.toUpperCase()}</span><p>{view.isolate?structure?.name??organNames[selected]:preset.description}</p></div>
   <div className="physical-search"><Search size={14}/><input aria-label="Search physical anatomy" placeholder="Find a structure…" value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>{if(e.key==='Escape')setQuery('');}}/>{query&&<button aria-label="Clear anatomy search" onClick={()=>setQuery('')}><X size={13}/></button>}{query.trim().length>=2&&<div className="physical-results">{searchResults.length?searchResults.map(c=><button key={c.id} onClick={()=>selectStructure(c)}><span>{c.name}</span><small>{c.elements.length} {c.elements.length===1?'part':'parts'}</small><ChevronRight size={12}/></button>):<p>No source structure found.</p>}</div>}</div>
   <div className="physical-orientation" aria-label="Anatomy camera angle">{(['front','oblique','back','side'] as AnatomyAngle[]).map(angle=><button key={angle} aria-pressed={view.angle===angle} onClick={()=>setView(v=>({...v,angle}))}>{angle==='front'?'Anterior':angle==='back'?'Posterior':angle==='side'?'Lateral':'¾ view'}</button>)}</div>
   <div className="physical-regions" role="group" aria-label="Anatomy region">{([{id:'body',name:'Full body'},{id:'torso',name:'Thorax'},{id:'abdomen',name:'Abdomen'},{id:'head',name:'Head & neck'}] as {id:AnatomyRegion;name:string}[]).map(r=><button key={r.id} aria-pressed={view.region===r.id&&!view.isolate} onClick={()=>setView(v=>({...v,region:r.id,isolate:false,focus:v.focus+1}))}>{r.name}</button>)}</div>
   <div className="physical-stage-actions"><button aria-label={motion?'Pause anatomical motion':'Play anatomical motion'} aria-pressed={motion} onClick={()=>setMotion(v=>!v)}>{motion?<Pause size={14}/>:<Play size={14}/>}<span>Motion</span></button><button onClick={()=>setToolsOpen(v=>!v)} aria-expanded={toolsOpen}><SlidersHorizontal size={15}/> Dissect</button><button aria-label="Reset anatomy view" onClick={reset}><RotateCcw size={15}/></button></div>
   {toolsOpen&&<div className="physical-tools"><div><strong>Dissection controls</strong><button aria-label="Close dissection controls" onClick={()=>setToolsOpen(false)}><X size={13}/></button></div><label>Section plane<select aria-label="Anatomical section plane" value={view.cut} onChange={e=>setView(v=>({...v,cut:e.target.value as PhysicalViewState['cut']}))}><option value="none">None</option><option value="sagittal">Sagittal · left / right</option><option value="coronal">Coronal · front / back</option><option value="axial">Axial · upper / lower</option></select></label>{view.cut!=='none'&&<label>Section position<input aria-label="Anatomical section position" type="range" min="0" max="1" step=".01" value={view.slice} onChange={e=>setView(v=>({...v,slice:Number(e.target.value)}))}/></label>}<label>Skeleton context<input aria-label="Skeleton context opacity" type="range" min="0" max="1" step=".05" value={view.context} onChange={e=>setView(v=>({...v,context:Number(e.target.value)}))}/></label><p>Context opacity applies to Organs, Vessels and Nerves. Section planes expose source surfaces; cut faces are open.</p>{view.hidden.length>0&&<button onClick={()=>setView(v=>({...v,hidden:[]}))}>Restore {view.hidden.length} hidden parts</button>}</div>}
   {progress<100&&!displayError&&<div className="physical-loading" role="status"><Layers3 size={25}/><strong>Assembling the anatomy</strong><span>{progress}% · Loading source geometry</span><div><i style={{width:`${progress}%`}}/></div></div>}
   {displayError&&<div className="physical-loading physical-load-error" role="alert"><strong>{displayError}</strong><button onClick={()=>onAnatomy()}>Open anatomy workspace <ArrowUpRight size={14}/></button></div>}
   <div className="physical-tracer-legend"><span><i/> O₂-rich blood</span><span><i/> O₂-poor blood</span><span><i/> Air</span><span><i/> Food / nutrients</span></div><div className="physical-scale" aria-hidden="true"><i/><span>SUPERIOR</span><span>INFERIOR</span></div>
   <div className="physical-stage-foot"><span>{motion?'Cycles at current rates':'Motion paused'} · {running?'Simulation running':'State preview'}</span><span>Drag to orbit · Scroll to zoom · Click to inspect</span></div>
  </div>
  <div className="physical-pathway" aria-label="Live process connections">
   {selected==='gut'?<><div><span>01 · STOMACH</span><strong>{(state.stomach.carbs+state.stomach.protein+state.stomach.fat).toFixed(1)} g</strong><small>Pepsin {state.enzymes.pepsin.toFixed(2)}×</small></div><ChevronRight/><div><span>02 · INTESTINE</span><strong>{(state.gut.carbs+state.gut.protein+state.gut.fat).toFixed(1)} g</strong><small>Amylase {state.enzymes.amylase.toFixed(2)}× · Lipase {state.enzymes.lipase.toFixed(2)}×</small></div><ChevronRight/><div><span>03 · ABSORPTION</span><strong>{(state.digestionRates.carbs+state.digestionRates.protein).toFixed(2)} g/min</strong><small>Glucose + amino acids → portal blood</small></div><ChevronRight/><div><span>04 · FEEDBACK</span><strong>Insulin {state.hormones.insulin.toFixed(2)}×</strong><small>Fat → lymph: {state.digestionRates.fat.toFixed(2)} g/min</small></div></>:
   selected==='lungs'?<><div><span>01 · VENTILATION</span><strong>{(state.respiratoryRate*state.tidalVolume/1000).toFixed(1)} L/min</strong><small>Air → trachea → bronchi</small></div><ChevronRight/><div><span>02 · PULMONARY FLOW</span><strong>{state.cardiacOutput.toFixed(2)} L/min</strong><small>Right heart → lungs → left heart</small></div><ChevronRight/><div><span>03 · ARTERIAL BLOOD</span><strong>{state.saturation.toFixed(1)}% O₂</strong><small>CO₂ pressure {state.paCO2.toFixed(1)} mmHg</small></div></>:
   <><div><span>01 · THE PUMP</span><strong>{state.strokeVolume.toFixed(0)} mL / beat</strong><small>{state.heartRate.toFixed(0)} beats each minute</small></div><ChevronRight/><div><span>02 · CIRCULATION</span><strong>{state.cardiacOutput.toFixed(2)} L/min</strong><small>Arteries → organ beds → veins</small></div><ChevronRight/><div><span>03 · TISSUE USE</span><strong>{state.oxygenConsumption.toFixed(0)} mL O₂/min</strong><small>Oxygen use across organ compartments</small></div></>}
  </div>
  <p className="physical-motion-note">Motion illustrates current model rates. Tracer size, paths and transit timing are simplified; particles remain visible through tissues.</p>
  <div className="physical-selection"><div><span>{structure?'SELECTED STRUCTURE':'SELECTED PHYSIOLOGY'}</span><h3>{structure?.name??organNames[selected]}</h3><p>{parts.length?`${parts.length.toLocaleString()} source ${parts.length===1?'mesh':'meshes'}${structure?` · ${structure.id}`:''}`:'No dedicated geometry in this atlas'}</p>{parts.some(id=>id.startsWith('BP3D3-'))&&<p className="physical-reference-note">Includes 3.0 lung reference surfaces · approximate alignment</p>}</div><div className="physical-selection-actions"><button disabled={!parts.length} onClick={()=>setView(v=>({...v,region:'selection',focus:v.focus+1}))}><Focus size={14}/> Focus</button><button disabled={!parts.length} aria-pressed={view.isolate} onClick={()=>setView(v=>({...v,isolate:!v.isolate,region:!v.isolate?'selection':'body',focus:v.focus+1,cut:'none'}))}><Eye size={14}/> {view.isolate?'In context':'Isolate'}</button>{structure&&<button onClick={()=>{setView(v=>({...v,hidden:[...new Set([...v.hidden,...parts])],isolate:false,region:v.region==='selection'?'body':v.region}));setStructure(null);}}>Hide</button>}<button aria-label="Open selected structure in full atlas" onClick={()=>onAnatomy(structure?.name??({gut:'small intestine',muscle:'skeletal muscle',endocrine:'pituitary gland',kidneys:'kidney',lungs:'lung'} as Partial<Record<Organ,string>>)[selected]??organNames[selected])}><ArrowUpRight size={16}/></button></div></div>
  <div className="physical-live-heading"><span><i/> LIVE ORGAN READOUTS</span><small>{layer==='flow'?'Blood flow':layer==='oxygen'?'Oxygen use':'Relative hormone activity'} · organ compartments</small></div>
  <div className="physical-organ-list">{organs.map(id=><button key={id} aria-label={`Inspect ${organNames[id]}`} aria-pressed={selected===id&&!structure} onClick={()=>selectOrgan(id)}><span>{organNames[id]}</span><strong>{value(id)}</strong></button>)}</div>
  <div className="physical-credit"><span>{atlas?.parts.length.toLocaleString()??'2,273'} source meshes · {SYSTEMS.length} systems · {((atlas?.triangles??2548238)/1000000).toFixed(2)}M triangles</span><a href="/ATTRIBUTION.md" target="_blank" rel="noreferrer">Source & attribution ↗</a></div>
 </div>;
}
