import type {Scenario} from './types';
export const scenarios:Scenario[]=[
  {id:'baseline',name:'Resting body',description:'Observe fasting feedback, circulation, and water loss without an intervention.',duration:3600,events:[]},
  {id:'meal',name:'After a meal',description:'Follow a mixed meal through digestion, absorption, insulin, and hepatic storage over three hours.',duration:10800,events:[{at:0,label:'Mixed meal',action:{kind:'meal',meal:{carbs:75,protein:25,fat:20,water:350,sodium:600}}}]},
  {id:'exercise',name:'Exercise & recovery',description:'Warm up, sustain a 20-minute workload, then watch cardiac, respiratory, and hormone recovery.',duration:3600,events:[{at:120,label:'Begin moderate exercise',action:{kind:'environment',values:{exercise:.5}}},{at:1320,label:'Begin recovery',action:{kind:'environment',values:{exercise:0}}},{at:1500,label:'Drink 400 mL water',action:{kind:'meal',meal:{carbs:0,protein:0,fat:0,water:400,sodium:0}}}]},
  {id:'stress',name:'Startle & settle',description:'A brief sound and pain input recruits autonomic drive, then the slower HPA stress axis.',duration:3600,events:[{at:120,label:'Sensory stress for 2 minutes',action:{kind:'environment',values:{sound:.9,pain:.4}}},{at:240,label:'Stimulus removed',action:{kind:'environment',values:{sound:0,pain:0}}}]},
  {id:'air',name:'Changing the air',description:'Reduce inspired oxygen for ten minutes; follow gas exchange and chemoreflex feedback.',duration:1800,events:[{at:120,label:'Inspired oxygen 15%',action:{kind:'environment',values:{oxygen:.15}}},{at:720,label:'Return to room air',action:{kind:'environment',values:{oxygen:.2095}}}]},
  {id:'water',name:'Water & kidneys',description:'A 750 mL drink expands fluid volume; osmolarity, ADH, ANP, and urine output respond.',duration:10800,events:[{at:0,label:'Drink 750 mL water',action:{kind:'meal',meal:{carbs:0,protein:0,fat:0,water:750,sodium:0}}}]},
  {id:'sleep',name:'An evening into sleep',description:'Fast-forward to evening, dim the lights, and observe melatonin and the simplified growth axis.',duration:86400,events:[{at:43200,label:'Dim evening light',action:{kind:'environment',values:{light:.05}}},{at:50400,label:'Sleep opportunity',action:{kind:'environment',values:{sleep:1}}},{at:79200,label:'Wake to daylight',action:{kind:'environment',values:{sleep:0,light:.9}}}]},
];
