import {useEffect,useMemo,useRef,useState} from 'react';
import {Activity,ArrowLeft,ArrowRight,Download,Droplets,Heart,Pause,Play,RotateCcw,Upload} from 'lucide-react';
import {BLOOD_NODES,DEFAULT_CIRCULATION,DURATION,exportCirculation,importCirculation,observeCirculation,type CirculationConfig,type CirculationResult,type NodeId} from './model';
import FlowMap from './FlowMap';
import Curves from './Curves';
import TissueScene,{type TissueView} from '../tissue/TissueScene';
import {loadTissueManifest,type TissueManifest} from '../tissue/assets';
import {SARCOMERE} from '../tissue/sarcomere';
import '../tissue/tissue.css';
import './circulation.css';
const clock=(s:number)=>`${Math.floor(s/60).toString().padStart(2,'0')}:${Math.floor(s%60).toString().padStart(2,'0')}`;
export default function CirculationLab({onBack,onTissue}:{onBack:()=>void;onTissue:()=>void}){
 const [draft,setDraft]=useState({...DEFAULT_CIRCULATION}),[job,setJob]=useState({config:{...DEFAULT_CIRCULATION},time:0}),[result,setResult]=useState<CirculationResult|null>(null),[computing,setComputing]=useState(true),[error,setError]=useState('');
 const [time,setTime]=useState(0),[playing,setPlaying]=useState(false),[speed,setSpeed]=useState(1),[selected,setSelected]=useState<NodeId>('portal'),[scale,setScale]=useState<'flow'|'fiber'>('flow'),[mapZoom,setMapZoom]=useState(false);
 const [manifest,setManifest]=useState<TissueManifest|null>(null),[assetError,setAssetError]=useState(''),[entity,setEntity]=useState('pilot-myofibrils'),[section,setSection]=useState(false),[sheath,setSheath]=useState(true),[angle,setAngle]=useState<TissueView['angle']>('oblique'),[notice,setNotice]=useState('');
 const [reducedMotion,setReducedMotion]=useState(()=>window.matchMedia('(prefers-reduced-motion: reduce)').matches),file=useRef<HTMLInputElement>(null);
 useEffect(()=>{const media=window.matchMedia('(prefers-reduced-motion: reduce)'),change=()=>setReducedMotion(media.matches);media.addEventListener('change',change);return()=>media.removeEventListener('change',change);},[]);
 useEffect(()=>{
  setComputing(true);setError('');let worker:Worker;
  try{worker=new Worker(new URL('./circulation.worker.ts',import.meta.url),{type:'module'});}catch{setError('The circulation worker is unavailable.');setComputing(false);return;}
  worker.onmessage=({data}:{data:{result?:CirculationResult;error?:string}})=>{setComputing(false);if(data.result){setResult(data.result);setTime(job.time);setPlaying(false);}else setError(data.error??'Circulation calculation failed.');};
  worker.onerror=()=>{setComputing(false);setError('The circulation worker stopped. The prior experiment is retained.');};worker.postMessage({id:1,config:job.config});return()=>worker.terminate();
 },[job]);
 useEffect(()=>{if(!playing||!result||computing)return;let frame=0,last=performance.now();const tick=(now:number)=>{const dt=Math.min(.25,(now-last)/1000);last=now;setTime(t=>Math.min(DURATION,t+dt*speed));frame=requestAnimationFrame(tick);};frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame);},[playing,speed,result,computing]);
 useEffect(()=>{if(time>=DURATION)setPlaying(false);},[time]);
 useEffect(()=>{if(scale!=='fiber'||manifest)return;const abort=new AbortController();setAssetError('');loadTissueManifest(abort.signal).then(setManifest).catch(e=>{if(!abort.signal.aborted)setAssetError((e as Error).message);});return()=>abort.abort();},[scale,manifest]);
 useEffect(()=>{if(!notice)return;const id=setTimeout(()=>setNotice(''),4000);return()=>clearTimeout(id);},[notice]);
 const sample=result?observeCirculation(result,time):null,node=BLOOD_NODES.find(n=>n.id===selected)!,nodeIndex=BLOOD_NODES.indexOf(node);
 const tissueView=useMemo<TissueView>(()=>({selected:entity,showSheath:sheath,showBone:false,section:section?'longitudinal':'none',slice:.5,reset:0,angle,signal:true,glut4:sample?.signal[20]??4,sarcomereLength:SARCOMERE.rest}),[entity,sheath,section,angle,sample?.signal[20]]);
 const start=(config:CirculationConfig,at:number)=>{setComputing(true);setPlaying(false);setJob({config:{...config},time:at});};
 const apply=()=>start(draft,0);
 const save=()=>{if(!result)return;const url=URL.createObjectURL(new Blob([exportCirculation(result.config,time)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='human-atlas-circulation.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setNotice('Circulation settings and playhead saved.');};
 return <div className="tissue-app circulation-app">
  <header className="tissue-header"><button className="tissue-brand" onClick={onBack}><span><Activity size={22}/></span><b>Human Atlas<small>CIRCULATION LAB</small></b></button><button className="tissue-back" onClick={onBack}><ArrowLeft size={14}/> Whole-body physiology</button><button className="tissue-back tissue-molecular-link" onClick={onTissue}>Tissue explorer <ArrowRight size={14}/></button></header>
  <main><div className="tissue-intro"><div><span className="tissue-eyebrow">FROM DELIVERY TO LOCAL RESPONSE</span><h1>A hormone, in circulation.</h1><p>Follow a pulse through blood, liver and muscle. See what changes when its route or clearance changes.</p></div><span className="circ-prototype">EXPERIMENTAL MODEL<small>Physical quantities · synthetic parameters</small></span></div>
   <section className="circ-controls" aria-label="Circulation experiment settings">
    <label>Pulse route<select aria-label="Insulin pulse route" value={draft.route} onChange={e=>setDraft(d=>({...d,route:e.target.value as CirculationConfig['route']}))}><option value="portal">Portal vein → liver first</option><option value="venous">Systemic vein → lungs first</option></select></label>
    <label>Pulse amount <output>{draft.dosePmol.toFixed(0)} pmol</output><input aria-label="Insulin pulse amount" type="range" min="0" max="5000" step="100" value={draft.dosePmol} onChange={e=>setDraft(d=>({...d,dosePmol:Number(e.target.value)}))}/></label>
    <label>Hepatic clearance <output>{draft.hepaticClearance.toFixed(1)}×</output><input aria-label="Hepatic clearance multiplier" type="range" min="0" max="2" step=".1" value={draft.hepaticClearance} onChange={e=>setDraft(d=>({...d,hepaticClearance:Number(e.target.value)}))}/></label>
    <label>Tissue exchange <output>{draft.exchange.toFixed(1)}×</output><input aria-label="Muscle insulin exchange" type="range" min="0" max="2" step=".1" value={draft.exchange} onChange={e=>setDraft(d=>({...d,exchange:Number(e.target.value)}))}/></label>
    <label>Muscle resistance <output>{draft.muscleResistance.toFixed(1)}×</output><input aria-label="Muscle vascular resistance" type="range" min=".5" max="2.5" step=".1" value={draft.muscleResistance} onChange={e=>setDraft(d=>({...d,muscleResistance:Number(e.target.value)}))}/></label>
    <button onClick={apply} disabled={computing}><RotateCcw size={14}/> Run experiment</button>
   </section>
   <div className="circ-run-status" role="status">{computing?'Calculating circulation…':result?`Experiment ready · ${result.config.dosePmol} pmol into the ${result.config.route==='portal'?'portal':'systemic'} vein, from 5–25 seconds.`:'No result available.'}{result&&computing&&' Previous result shown until this run succeeds.'}</div>
   {error&&<p className="circ-error" role="alert">{error}</p>}
   {result&&sample&&<>
    <section className="circ-workspace">
     <div className="circ-main"><div className="circ-view-header"><div role="tablist" aria-label="Circulation scale"><button role="tab" aria-selected={scale==='flow'} onClick={()=>setScale('flow')}><Droplets size={15}/> Flow map</button><button role="tab" aria-selected={scale==='fiber'} onClick={()=>setScale('fiber')}>Muscle fiber</button></div><span>One numerical trajectory across views</span></div>
      {scale==='flow'?<div className="circ-map-wrap"><div className="circ-map-toolbar"><span>{mapZoom?'Scroll horizontally to inspect the map':'Select a compartment to inspect its contents'}</span><button aria-pressed={mapZoom} onClick={()=>setMapZoom(!mapZoom)}>{mapZoom?'Fit map':'Enlarge map'}</button></div><div className={`circ-map-scroll ${mapZoom?'zoomed':''}`}><FlowMap sample={sample} selected={selected} onSelect={setSelected} reducedMotion={reducedMotion}/></div><p>Modeled connections, drawn schematically. Tracer spacing shows transfer; it does not measure vessel velocity or count molecules.</p></div>:<div className="circ-fiber"><div className="tissue-stage">
       {manifest?<TissueScene asset={manifest.levels.fiber.representations.detail} level="fiber" view={tissueView} onSelect={setEntity} onReady={()=>{}} onMetrics={()=>{}} onError={setAssetError}/>:<div className="tissue-stage-loading">Loading the representative fiber…</div>}
       {assetError&&<div className="tissue-stage-error" role="alert">{assetError}</div>}
       <div className="tissue-stage-caption"><span>Muscle fiber · representative geometry</span><small>GLUT4 brightness follows the local interstitial input</small></div><div className="tissue-view-tools"><button onClick={()=>setAngle(angle==='end'?'oblique':'end')}>{angle==='end'?'Oblique view':'Cut end'}</button></div>
      </div><div className="circ-fiber-controls"><label>Structure<select aria-label="Circulation tissue structure" value={entity} onChange={e=>setEntity(e.target.value)}>{manifest?.entities.filter(e=>e.level==='fiber').map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select></label><label><input type="checkbox" checked={sheath} onChange={e=>setSheath(e.target.checked)}/> Outer sheath</label><label><input type="checkbox" checked={section} onChange={e=>setSection(e.target.checked)}/> Section</label></div></div>}
      <div className="circ-playback"><button aria-label={playing?'Pause circulation':'Play circulation'} disabled={computing} onClick={()=>{if(time>=DURATION)setTime(0);setPlaying(!playing);}}>{playing?<Pause size={16}/>:<Play size={16}/>}</button><strong aria-label="Circulation elapsed time">{clock(time)}</strong><span>/ 10:00</span><input aria-label="Circulation time" disabled={computing} type="range" min="0" max={DURATION} step=".1" value={time} onChange={e=>{setTime(Number(e.target.value));setPlaying(false);}}/><select aria-label="Circulation playback speed" value={speed} onChange={e=>setSpeed(Number(e.target.value))}><option value=".25">¼×</option><option value="1">1×</option><option value="5">5×</option><option value="20">20×</option></select><button aria-label="Rewind circulation" onClick={()=>{setPlaying(false);setTime(0);}}><RotateCcw size={14}/></button></div>
      <Curves result={result} time={time}/>
     </div>
     <aside className="circ-inspector"><span className="tissue-eyebrow">FOLLOW THE MATERIAL</span><label className="tissue-field">Compartment<select aria-label="Inspect circulation compartment" value={selected} onChange={e=>setSelected(e.target.value as NodeId)}>{BLOOD_NODES.map(n=><option key={n.id} value={n.id}>{n.name}</option>)}</select></label><h2>{node.name}</h2><p>{node.description}</p>
      <div className="circ-readouts"><div><span>Insulin in plasma</span><strong aria-label="Selected plasma insulin">{sample.insulinPM[nodeIndex].toFixed(1)}<small> pM</small></strong></div><div><span>Local pressure</span><strong>{sample.pressureMmHg[nodeIndex].toFixed(1)}<small> mmHg</small></strong></div><div><span>Blood volume</span><strong>{(sample.volumesL[nodeIndex]*1000).toFixed(1)}<small> mL</small></strong></div></div>
      <div className="circ-local-response"><Heart size={16}/><span className="tissue-eyebrow">MUSCLE RESPONSE</span><dl><div><dt>Interstitial insulin</dt><dd aria-label="Muscle interstitial insulin">{sample.interstitialPM.toFixed(1)} pM</dd></div><div><dt>Active Akt</dt><dd>{sample.signal[16].toFixed(2)} % pool</dd></div><div><dt>Surface GLUT4</dt><dd aria-label="Circulation surface GLUT4">{sample.signal[20].toFixed(2)} % pool</dd></div></dl><p>The archived signaling pathway now receives the local insulin concentration. It remains a mixed-preparation model; no muscle glucose uptake is added.</p></div>
      <div className="circ-ledger"><span className="tissue-eyebrow">INSULIN ACCOUNTING · PMOL</span><dl>{[['Delivered',sample.injectedPmol],['In blood',sample.circulatingPmol],['In interstitium',sample.interstitialPmol],['Cleared by liver',sample.clearedPmol[0]],['Cleared by kidney',sample.clearedPmol[1]],['Cleared locally',sample.clearedPmol[2]]].map(([name,value])=><div key={name}><dt>{name}</dt><dd>{Number(value).toFixed(2)}</dd></div>)}</dl><small>Injected = blood + tissue + cleared</small></div>
     </aside>
    </section>
    <details className="tissue-provenance"><summary>Equations, units and evidence</summary><p>Ten compliant blood compartments. Pressure follows volume/compliance; passive flow follows pressure difference/resistance. Left and right pump waveforms are prescribed at 72 beats/min and 5 L/min mean output. Valves and cardiac mechanics are not modeled here.</p><p>Hematocrit is fixed at 45%. The 5 L blood inventory contains 2.75 L plasma and 2.25 L erythrocyte volume. Insulin occupies plasma and the 0.5 L effective muscle interstitial compartment. Exchange moves insulin without transferring water. Clearance coefficients and vascular parameters are synthetic engineering choices.</p><p>Maximum blood-volume residual: {result.maximumVolumeResidualL.toExponential(2)} L. Maximum insulin-ledger residual: {result.maximumInsulinResidualMol.toExponential(2)} mol. These verify accounting, not agreement with a living human.</p><p>The detailed tissue is representative. Source receptor states observe insulin without consuming the physical inventory. This experiment does not replace the existing whole-body engine or duplicate its uptake. Oxygen/CO₂ chemistry, physiological secretion, human parameter calibration and physical flow within the depicted capillary remain unimplemented.</p><a href="https://models.physiomeproject.org/e/43/MainWindKessel.cellml/view" target="_blank" rel="noreferrer">Lumped circulation reference ↗</a><a href="https://pmc.ncbi.nlm.nih.gov/articles/PMC7824884/" target="_blank" rel="noreferrer">Insulin clearance experiment ↗</a></details>
    <div className="tissue-files"><button onClick={save} disabled={computing}><Download size={14}/> Save circulation experiment</button><button onClick={()=>file.current?.click()}><Upload size={14}/> Load circulation experiment</button><span>Recomputes the same model and restores paused</span></div>
   </>}
   <input ref={file} type="file" hidden accept=".json,application/json" aria-label="Import circulation experiment" onChange={async e=>{const input=e.target,f=input.files?.[0];if(!f)return;try{if(f.size>100000)throw new Error('Circulation recording exceeds 100 kB.');const data=importCirculation(await f.text());setDraft(data.config);start(data.config,data.time);setNotice('Recomputing the saved circulation experiment.');}catch(e){setError((e as Error).message);}input.value='';}}/>
   <footer className="tissue-footer">HUMAN ATLAS / PHYSICAL TRANSPORT <span>Experimental circulation · human validation pending</span></footer>
  </main>{notice&&<div className="tissue-notice" role="status">{notice}</div>}
 </div>;
}
