/**
 * Resting adult plasma concentrations (mol/L) and blood cell counts used to turn the body model's
 * levels into amounts. GENERATED by scripts/molecules/reference.py from
 * assets/molecules/blood-reference.json, which holds every range, conversion and source.
 *
 * `trust`: 'cited' is a reported mean or mid-range from a source that was opened; 'approximate' rests
 * on an assumed typical value, an assumed unit conversion or a source read only in excerpt, and may
 * be off severalfold; 'none' means no usable blood value was found and the species is not drawn.
 */
export type Reference={molar?:number|null;molarPerMmHg?:number;perMicrolitre?:number;trust:'cited'|'approximate'|'none';reported:string;url:string};
export const REFERENCE:Record<string,Reference>={
 insulin:{molar:5.588e-11,trust:'approximate',reported:'8.0 uIU/mL = geometric mean of Mayo range (typical not stated by source)',url:'https://www.mayocliniclabs.com/test-catalog/overview/8664/insulin-serum'},
 glucagon:{molar:2.296e-11,trust:'approximate',reported:'Source gives only upper limit; 80 pg/mL (half the upper limit) used as ASSUMED typical',url:'https://mlabs.umich.edu/tests/glucagon-plasma'},
 epinephrine:{molar:1.365e-10,trust:'approximate',reported:'Source gives upper limits only; 25 pg/mL (half of <50) ASSUMED typical',url:'https://www.abim.org/Media/bfijryql/laboratory-reference-ranges.pdf'},
 norepinephrine:{molar:1.605e-09,trust:'cited',reported:'271 pg/mL = geometric mean of 112-658 (typical not stated)',url:'https://www.abim.org/Media/bfijryql/laboratory-reference-ranges.pdf'},
 crh:{molar:1.328e-12,trust:'approximate',reported:'~6 pg/mL',url:'https://jci.org/articles/view/112204'},
 acth:{molar:5.395e-12,trust:'cited',reported:'24.5 pg/mL = geometric mean of range; morning peak, falls through day',url:'https://www.abim.org/Media/bfijryql/laboratory-reference-ranges.pdf'},
 cortisol:{molar:3.086e-07,trust:'cited',reported:'11.2 ug/dL = geometric mean of 8 AM range',url:'https://www.abim.org/Media/bfijryql/laboratory-reference-ranges.pdf'},
 trh:{molar:null,trust:'none',reported:'No trustworthy typical value',url:'https://www.jci.org/articles/view/107339'},
 tsh:{molar:5.893e-12,trust:'approximate',reported:'1.41 mIU/L = geometric mean of range',url:'https://www.abim.org/Media/bfijryql/laboratory-reference-ranges.pdf'},
 thyroid:{molar:1.848e-09,trust:'cited',reported:'120 ng/dL = geometric mean',url:'https://www.abim.org/Media/bfijryql/laboratory-reference-ranges.pdf'},
 adh:{molar:2.167e-12,trust:'approximate',reported:'Source gives upper limit only; 2.35 pg/mL (half the Labcorp upper limit) ASSUMED typical',url:'https://www.labcorp.com/test-menu/20066/antidiuretic-hormone-adh-plasma'},
 renin:{molar:null,trust:'none',reported:'No direct renin concentration source found',url:'https://www.abim.org/Media/bfijryql/laboratory-reference-ranges.pdf'},
 angiotensin:{molar:1.85e-11,trust:'approximate',reported:'18.5 pM',url:'https://clinicalproteomicsjournal.biomedcentral.com/articles/10.1186/1559-0275-11-37'},
 aldosterone:{molar:1.385e-10,trust:'approximate',reported:'Source gives upper limit only; 5 ng/dL (half of 10) ASSUMED typical',url:'https://www.abim.org/Media/bfijryql/laboratory-reference-ranges.pdf'},
 anp:{molar:5.783e-12,trust:'approximate',reported:'17.8 pg/mL',url:'https://www.degruyterbrill.com/document/doi/10.1515/CCLM.2002.060/pdf'},
 gastrin:{molar:2.383e-11,trust:'approximate',reported:'Upper limit only; 50 pg/mL ASSUMED typical',url:'https://www.abim.org/Media/bfijryql/laboratory-reference-ranges.pdf'},
 secretin:{molar:1.2e-12,trust:'approximate',reported:'1.2 pmol/L',url:'https://sharpelab.hms.harvard.edu/publications/plasma-secretin-concentrations-fasting-and-postprandial-state-man'},
 cck:{molar:1.035e-11,trust:'approximate',reported:'Upper limit only; 40 pg/mL ASSUMED typical',url:'https://www.mayocliniclabs.com/test-catalog/overview/75914/cholecystokinin-cck'},
 glp1:{molar:3.23e-12,trust:'approximate',reported:'3.2 pmol/L total (0.8 pmol/L active)',url:'https://bmcendocrdisord.biomedcentral.com/articles/10.1186/s12902-024-01566-9/tables/1'},
 ghrelin:{molar:1.46e-10,trust:'approximate',reported:'146 fmol/mL = 146 pmol/L',url:'https://pubmed.ncbi.nlm.nih.gov/17492951'},
 leptin:{molar:1.204e-10,trust:'cited',reported:'1.93 ng/mL = geometric mean of male range',url:'https://mlabs.umich.edu/tests/leptin'},
 melatonin:{molar:8.61e-12,trust:'cited',reported:'Daytime ~2.0 pg/mL; night peak ~70 pg/mL (geometric mean of 50-100, my choice)',url:'https://pmc.ncbi.nlm.nih.gov/articles/PMC2856692'},
 gh:{molar:4.52e-11,trust:'approximate',reported:'Upper limit only; 1 ng/mL ASSUMED order-of-magnitude typical',url:'https://www.abim.org/Media/bfijryql/laboratory-reference-ranges.pdf'},
 igf1:{molar:3.096e-08,trust:'cited',reported:'237 ng/mL = geometric mean of the 25-39 range',url:'https://www.abim.org/Media/bfijryql/laboratory-reference-ranges.pdf'},
 gnrh:{molar:null,trust:'none',reported:'N/A',url:'https://www.glowm.com/section-view/heading/Gonadotropin-releasing-Hormone-GnRH-and-the-GnRH-Receptor-GnRHR/item/284'},
 lh:{molar:1.463e-11,trust:'approximate',reported:'4.24 IU/L = geometric mean of range',url:'https://www.abim.org/Media/bfijryql/laboratory-reference-ranges.pdf'},
 fsh:{molar:8.268e-12,trust:'approximate',reported:'2.65 IU/L = geometric mean of range',url:'https://www.abim.org/Media/bfijryql/laboratory-reference-ranges.pdf'},
 testosterone:{molar:1.963e-08,trust:'cited',reported:'566 ng/dL = geometric mean',url:'https://www.abim.org/Media/bfijryql/laboratory-reference-ranges.pdf'},
 inhibin:{molar:4.193e-12,trust:'approximate',reported:'134 pg/mL = geometric mean of 8-30 y range (typical not stated)',url:'https://billingscliniclaboratory.testcatalog.org/show/Billings-Clinic-9566-Mayo-INHB'},
 pth:{molar:2.705e-12,trust:'cited',reported:'25.5 pg/mL = geometric mean',url:'https://www.abim.org/Media/bfijryql/laboratory-reference-ranges.pdf'},
 calcitriol:{molar:7.2e-11,trust:'cited',reported:'30 pg/mL = geometric mean',url:'https://www.abim.org/Media/bfijryql/laboratory-reference-ranges.pdf'},
 aminoAcids:{molar:0.00225,trust:'approximate',reported:'~2.25 mmol/L (midpoint)',url:'https://pmc.ncbi.nlm.nih.gov/articles/PMC8562079/table/tbl3'},
 lipids:{molar:0.000214,trust:'cited',reported:'214 nmol/mL = 0.214 mmol/L',url:'https://bionumbers.hms.harvard.edu/bionumber.aspx?id=110992'},
 carbonDioxide:{molar:0.001228,molarPerMmHg:3.07e-05,trust:'approximate',reported:'1.23 mmol/L at PaCO2 40 mmHg',url:'https://en.wikipedia.org/wiki/Henderson%E2%80%93Hasselbalch_equation'},
 sodium:{molar:0.14,trust:'cited',reported:'140 mmol/L',url:'https://www.abim.org/Media/bfijryql/laboratory-reference-ranges.pdf'},
 potassium:{molar:0.00425,trust:'cited',reported:'4.25 mmol/L = midpoint',url:'https://www.abim.org/Media/bfijryql/laboratory-reference-ranges.pdf'},
 chloride:{molar:0.102,trust:'cited',reported:'102 mmol/L = midpoint',url:'https://www.abim.org/Media/bfijryql/laboratory-reference-ranges.pdf'},
 bicarbonate:{molar:0.0245,trust:'cited',reported:'24.5 mmol/L = midpoint of arterial range',url:'https://www.abim.org/Media/bfijryql/laboratory-reference-ranges.pdf'},
 calcium:{molar:0.001235,trust:'cited',reported:'1.235 mmol/L = midpoint',url:'https://www.abim.org/Media/bfijryql/laboratory-reference-ranges.pdf'},
 albumin:{molar:0.0006767,trust:'cited',reported:'45.0 g/L = chosen typical (midpoint-ish)',url:'https://www.abim.org/Media/bfijryql/laboratory-reference-ranges.pdf'},
 igg:{molar:7.667e-05,trust:'cited',reported:'11.5 g/L = midpoint',url:'https://www.abim.org/Media/bfijryql/laboratory-reference-ranges.pdf'},
 fibrinogen:{molar:8.824e-06,trust:'cited',reported:'3.0 g/L = midpoint',url:'https://www.abim.org/Media/bfijryql/laboratory-reference-ranges.pdf'},
 redCell:{perMicrolitre:5.1e+06,trust:'cited',reported:'4.2-5.9 million/uL (ABIM, both sexes); men 5-6 million/uL (Wikipedia Red blood cell)',url:'https://bionumbers.hms.harvard.edu/bionumber.aspx?id=112779'},
 platelet:{perMicrolitre:250000,trust:'cited',reported:'150,000-450,000/uL (ABIM); 150,000-400,000 (Wikipedia Platelet)',url:'https://arxiv.org/pdf/0807.4673'},
 whiteCell:{perMicrolitre:7000,trust:'cited',reported:'4,000-11,000/uL (ABIM)',url:'https://www.abim.org/Media/bfijryql/laboratory-reference-ranges.pdf'},
};
