"""Download the structures named in assets/molecules/spec.json and reduce each to the atoms it shows.

  python3 scripts/molecules/fetch.py

Writes assets/molecules/source/<id>.json (element, position in angstrom, bonds where the source
gives them) and assets/molecules/ledger.json (what was downloaded, its hash, and what was kept).
Standard library only.
"""
import hashlib, json, pathlib, sys, time, urllib.request

ROOT = pathlib.Path(__file__).resolve().parents[2]
PACKAGE = ROOT / 'assets/molecules'
MASS = {'H': 1.008, 'C': 12.011, 'N': 14.007, 'O': 15.999, 'S': 32.06, 'I': 126.904, 'P': 30.974, 'SE': 78.971}

def get(url):
    for attempt in range(4):
        try:
            with urllib.request.urlopen(urllib.request.Request(url, headers={'User-Agent': 'biosim-molecules/0.1'}), timeout=60) as r:
                return r.read()
        except Exception as error:
            if attempt == 3: raise RuntimeError(f'{url}: {error}')
            time.sleep(2 ** attempt)

def pubchem(cid):
    url = f'https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/cid/{cid}/record/SDF?record_type=3d'
    raw = get(url)
    lines = raw.decode().splitlines()
    atoms_n, bonds_n = int(lines[3][:3]), int(lines[3][3:6])
    atoms = [[l.split()[3].upper(), float(l[:10]), float(l[10:20]), float(l[20:30])] for l in lines[4:4 + atoms_n]]
    bonds = [[int(l[:3]) - 1, int(l[3:6]) - 1, int(l[6:9])] for l in lines[4 + atoms_n:4 + atoms_n + bonds_n]]
    title = json.loads(get(f'https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/cid/{cid}/property/Title,MolecularFormula,MolecularWeight/JSON'))['PropertyTable']['Properties'][0]
    return raw, url, atoms, bonds, {'title': title['Title'], 'formula': title['MolecularFormula'], 'method': 'PubChem3D computed conformer', 'massDa': float(title['MolecularWeight'])}

def pdb(entry, chains):
    url = f'https://files.rcsb.org/download/{entry}.pdb'
    raw = get(url)
    atoms, seen, residues = [], set(), set()
    for line in raw.decode().splitlines():
        if line.startswith('ENDMDL'): break  # first model of an NMR ensemble
        if line[:6] not in ('ATOM  ', 'HETATM') or line[21] not in chains: continue
        if line[17:20] == 'HOH' or line[16] not in ' A': continue
        element = line[76:78].strip().upper() or line[12:14].strip().upper()
        if element in ('H', 'D'): continue
        key = (line[21], line[22:27], line[12:16])
        if key in seen: continue
        seen.add(key); residues.add((line[21], line[22:27]))
        atoms.append([element, float(line[30:38]), float(line[38:46]), float(line[46:54]), chains.index(line[21])])
    meta = json.loads(get(f'https://data.rcsb.org/rest/v1/core/entry/{entry}'))
    return raw, url, atoms, None, {'title': meta['struct']['title'], 'method': meta['exptl'][0]['method'], 'resolutionA': (meta['rcsb_entry_info'].get('resolution_combined') or [None])[0], 'residuesShown': len(residues), 'massDa': round(sum(MASS.get(a[0], 12) for a in atoms), 1), 'massNote': 'heavy atoms shown'}

spec = json.loads((PACKAGE / 'spec.json').read_text())
(PACKAGE / 'source').mkdir(exist_ok=True)
ledger = []
for m in spec['molecules']:
    if m['db'] == 'computed':
        # Ions and cells are generated by build.py from the published dimensions recorded here.
        if 'PENDING' in (m['citation'], m['url']): sys.exit(f"{m['id']}: add its citation to spec.json")
        source = {'id': m['id'], 'style': m['style'], **{k: m[k] for k in ('radiusA', 'color', 'shape') if k in m}}
        (PACKAGE / 'source' / f"{m['id']}.json").write_text(json.dumps(source, separators=(',', ':')) + '\n')
        ledger.append({'id': m['id'], 'name': m['name'], 'kind': m['kind'], 'style': m['style'], 'database': 'computed', 'accession': m['ref'], 'chains': None, 'url': m['url'],
                       'downloadSHA256': None, 'license': spec['licenses']['computed']['name'], 'standIn': False, 'note': m.get('note', ''), 'title': m['citation'], 'method': 'generated from published dimensions', 'massDa': None})
        print(f"{m['id']:15s} computed {m['ref']}")
        continue
    raw, url, atoms, bonds, info = pubchem(m['ref']) if m['db'] == 'pubchem' else pdb(m['ref'], m['chains'])
    if not atoms: sys.exit(f"{m['id']}: no atoms kept from {url}")
    # Centre on the centroid; the largest centre-to-atom distance sets the display scale later.
    c = [sum(a[i] for a in atoms) / len(atoms) for i in (1, 2, 3)]
    for a in atoms: a[1:4] = [round(a[i] - c[i - 1], 3) for i in (1, 2, 3)]
    radius = max((a[1] ** 2 + a[2] ** 2 + a[3] ** 2) ** .5 for a in atoms)
    source = {'id': m['id'], 'style': m['style'], 'atoms': atoms, 'bonds': bonds}
    (PACKAGE / 'source' / f"{m['id']}.json").write_text(json.dumps(source, separators=(',', ':')) + '\n')
    ledger.append({'id': m['id'], 'name': m['name'], 'kind': m['kind'], 'style': m['style'], 'database': m['db'], 'accession': m['ref'], 'chains': m.get('chains'), 'url': url,
                   'downloadSHA256': hashlib.sha256(raw).hexdigest(), 'license': spec['licenses'][m['db']]['name'], 'standIn': bool(m.get('standIn')), 'note': m.get('note', ''),
                   'atomsShown': len(atoms), 'radiusNm': round(radius / 10, 3), **info})
    print(f"{m['id']:15s} {m['db']:7s} {m['ref']:8s} atoms {len(atoms):5d} r {radius / 10:.2f} nm  {info['title'][:70]}")
(PACKAGE / 'ledger.json').write_text(json.dumps({'id': spec['id'], 'version': spec['version'], 'licenses': spec['licenses'], 'molecules': ledger}, indent=1) + '\n')
