"""Write app/physical/dive/reference.ts from assets/molecules/blood-reference.json.

  python3 scripts/molecules/reference.py

The JSON is the compiled table with every source, range and conversion. This script picks the one
number the app uses for each species and how far it can be trusted.
"""
import json, pathlib

ROOT = pathlib.Path(__file__).resolve().parents[2]
table = {e['id']: e for e in json.loads((ROOT / 'assets/molecules/blood-reference.json').read_text())['entries']}
# Species id in the app -> entry id in the table, where they differ.
ALIAS = {'aminoAcids': 'total_free_amino_acids', 'lipids': 'free_fatty_acids', 'calcium': 'calcium_ionized', 'redCell': 'red_cells', 'platelet': 'platelets', 'whiteCell': 'white_cells', 'carbonDioxide': 'dissolved_co2_arterial'}
HORMONES = 'insulin glucagon epinephrine norepinephrine crh acth cortisol trh tsh thyroid adh renin angiotensin aldosterone anp gastrin secretin cck glp1 ghrelin leptin melatonin gh igf1 gnrh lh fsh testosterone inhibin pth calcitriol'.split()
OTHERS = 'aminoAcids lipids carbonDioxide sodium potassium chloride bicarbonate calcium albumin igg fibrinogen redCell platelet whiteCell'.split()
# Entries whose page was opened and whose typical value is a reported mean or the middle of a reported range.
CITED = set('norepinephrine acth cortisol thyroid leptin igf1 testosterone pth calcitriol lipids sodium potassium chloride bicarbonate calcium albumin igg fibrinogen redCell platelet whiteCell melatonin'.split())
lines = []
for sid in HORMONES + OTHERS:
    e = table[ALIAS.get(sid, sid)]
    fields = []
    if 'count_per_uL' in e: fields.append(f"perMicrolitre:{e['count_per_uL']:g}")
    elif sid == 'carbonDioxide': fields.append(f"molar:{e['value_mol_per_L']:.4g},molarPerMmHg:{e['solubility_mmol_per_L_per_mmHg'] / 1000:.4g}")
    elif sid == 'albumin': fields.append(f"molar:{e['typical_g_per_L'] / 66500:.4g}")  # 66.5 kDa, the mass of the mature chain
    elif e.get('value_mol_per_L') is None: fields.append('molar:null')
    else: fields.append(f"molar:{e['value_mol_per_L']:.4g}")
    trust = 'none' if e.get('value_mol_per_L') is None and 'count_per_uL' not in e else 'cited' if sid in CITED else 'approximate'
    reported = (e.get('typical_reported') or e.get('count_range_reported') or e.get('range_reported') or '').replace("'", "\\'")
    lines.append(f" {sid}:{{{fields[0]},trust:'{trust}',reported:'{reported[:110]}',url:'{e['source_url']}'}},")
out = """/**
 * Resting adult plasma concentrations (mol/L) and blood cell counts used to turn the body model's
 * levels into amounts. GENERATED by scripts/molecules/reference.py from
 * assets/molecules/blood-reference.json, which holds every range, conversion and source.
 *
 * `trust`: 'cited' is a reported mean or mid-range from a source that was opened; 'approximate' rests
 * on an assumed typical value, an assumed unit conversion or a source read only in excerpt, and may
 * be off severalfold; 'none' means no usable blood value was found and the species is not drawn.
 */
export type Reference={molar?:number|null;molarPerMmHg?:number;perMicrolitre?:number;trust:'cited'|'approximate'|'none';reported:string;url:string};
export const REFERENCE:Record<string,Reference>={
""" + '\n'.join(lines) + "\n};\n"
(ROOT / 'app/physical/dive/reference.ts').write_text(out)
print('wrote reference.ts', len(lines))
